### ISSUE TITLE
Wrong signature for GModDataPack on Windows/SRCDS

### ISSUE THREAD

**Issue by xaviergmail** [danielga/gm_sourcenet#14]
Using the latest github release build

```
[ERROR] unable to find GModDataPack::SendFileToClient
  1. unknown - [C]:-1
   2. require - [C]:-1
    3. unknown - addons/xmod/lua/includes/sourcenet/server.lua:1
     4. include - [C]:-1
      5. unknown - addons/xmod/lua/includes/sourcenet/outgoing.lua:2
       6. include - [C]:-1
        7. unknown - addons/xmod/lua/includes/sourcenet/gameevents.lua:4
```

```
version
Protocol version 24
Exe version 18.12.05 (garrysmod)
Exe build: 15:58:05 Dec 15 2018 (7343) (4000)
```

**Comment by xaviergmail** [comment]
Furthermore, disabling the datapack integration on a local _unsupported_ 😮 build, the gameevent listener did not work. In fact, enabling sourcenet_netmessage_info, no outgoing packets were logged, only incoming. I don't know whether this warrants an issue of its own

**Comment by danielga** [comment]
@xaviergmail the failure to join the server issue is separate.

**Comment by xaviergmail** [comment]
I didn't have any issue joining, I just did not receive any callbacks for outgoing messages
