### ISSUE TITLE
Segfault trying using gameevents

### ISSUE THREAD

**Issue by xaviergmail** [danielga/gm_sourcenet#15]
Steps to reproduce:
1. `include "sourcenet/gameevents.lua"`
2. Join the server

Running a 32-bit Ubuntu 16.04.5, latest srcds

Output from dmesg, I can't seem to get any dumps spewed out by srcds_run
The first two were with builds straight from master branch, the third one is with the binary from GH releases
```
[ 3321.065494] srcds_linux[6459]: segfault at 95 ip ac292033 sp bffa6690 error 4 in gmsv_sourcenet_linux.dll[ac1fd000+20a000]
[ 3540.977394] srcds_linux[8026]: segfault at 95 ip ac99b033 sp bf9633f0 error 4 in gmsv_sourcenet_linux.dll[ac906000+20a000]
[ 4198.028331] srcds_linux[10060]: segfault at 10118 ip b5d8d565 sp bfdf54b0 error 4 in engine_srv.so[b5c1e000+2ce000]
```

**Comment by xaviergmail** [comment]
The same also happens on x84_64 debian sid

**Comment by danielga** [comment]
I believe this is fixed on the master branch.
