### ISSUE TITLE
Windows signatures need to be updated

### ISSUE THREAD

**Issue by xaviergmail** [danielga/gm_sourcenet#28]
`[ERROR] failed to locate CBaseClient::ConnectionStart`

**Comment by danielga** [comment]
What branch of Garry's Mod is this?

**Comment by GitSparTV** [comment]
Win32: `[ERROR] unable to find GModDataPack::SendFileToClient`

**Comment by GitSparTV** [comment]
Any plans for sourcenet signature fix?

**Comment by danielga** [comment]
Try [these builds](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.8) (when they're done).

**Comment by GitSparTV** [comment]
Still no builds

**Comment by GitSparTV** [comment]
Found in azure

**Comment by GitSparTV** [comment]
No errors on load

**Comment by danielga** [comment]
Resolved.
