### ISSUE TITLE
Failed to load required CSteamGameServerAPIContext interface.

### ISSUE THREAD

**Issue by owltaver** [danielga/gm_sourcenet#38]
![putty_UvfwbYw3yu](https://user-images.githubusercontent.com/52373664/86525150-07931500-be8c-11ea-9f38-1c85ef074038.png)
its happening only on newer version (1.1.9)
Debian 9.12

**Comment by Yogpod** [comment]
This also happens on windows with 1.1.9 compiled as 64bit
![image](https://user-images.githubusercontent.com/72334284/95553079-ae72da00-09c2-11eb-8f49-e834a20eba5b.png)

On linux64 it just crashes with no error message
![image](https://cdn.discordapp.com/attachments/565108080300261398/764010532121608222/unknown.png)

**Comment by danielga** [comment]
This should be fixed as of [v1.1.10](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.10)
