### ISSUE TITLE
failed to detour CNetChan::ProcessMessages

### ISSUE THREAD

**Issue by G-Force007** [danielga/gm_sourcenet#4]
Trying to run the examples sn_cheatskick.lua causes an instant server crash

[ERROR] addons/sourcenet_test/lua/sourcenet/server.lua:21: failed to detour CNetChan::ProcessMessages
  1. hook - [C]:-1
   2. StandardNetHook - addons/sourcenet_test/lua/sourcenet/server.lua:21
    3. AttachNetChannel - addons/sourcenet_test/lua/sourcenet/server.lua:30
     4. HookNetChannel - addons/sourcenet_test/lua/sourcenet/server.lua:74
      5. unknown - addons/sourcenet_test/lua/sourcenet/incoming.lua:11
       6. include - [C]:-1
        7. unknown - addons/sourcenet_test/lua/sourcenet/querycvar.lua:1

Server OS: Windows 2008 Server

**Comment by danielga** [comment]
I was unable to replicate this. Have you tried [this build](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.1)?
