### ISSUE TITLE
Voice chat instantly crashes the server

### ISSUE THREAD

**Issue by Yogpod** [danielga/gm_sourcenet#41]
happens on the updated lua branch, linux64 server running ubuntu 20.04
no error messages, it crashes before they can even print i assume

**Comment by danielga** [comment]
I wasn't able to reproduce a crash on Ubuntu 16.04 (WSL2) but that was because it wasn't even detouring the netmessages received. I believe I might've fixed that failure to detour but still wasn't able to reproduce a crash with voicechat.

**Comment by Yogpod** [comment]
One of your latest commits appears to have fixed my issue
