### ISSUE TITLE
Could we get aupdated set of prebuilt binaries

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gm_sourcenet#43]
I'd compile it myself but I'm currently not on a PC with vs/wsl installed and to install them would take several hours with the internet here

**Comment by VaasKahnGrim** [comment]
that and the latest prebuilt seems to not be working right for win32 server, main reason I'm asking

**Comment by danielga** [comment]
Latest builds being created [here](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.11).
