### ISSUE TITLE
sv_showlagcompensation crash

### ISSUE THREAD

**Issue by Yogpod** [danielga/gm_sourcenet#46]
how to reproduce:
start up server
spawn a bot
set sv_showlagcompensation to 1
click & server will crash
http://pls.propkill.me/5dFP.mp4

**Comment by danielga** [comment]
I'm unable to reproduce with the latest Lua code from the master branch.

**Comment by Yogpod** [comment]
probably should've mentioned i'm on the updated lua branch

**Comment by danielga** [comment]
> probably should've mentioned i'm on the updated lua branch on a linux64 server

That's not the up to date Lua branch, `[snmi]` prefixed debug messages don't exist anymore.

**Comment by danielga** [comment]
About the lag compensation convar crash, it's weird that it specifically requires that enabled and a bot ingame, doesn't seem to happen without a bot. Hopefully I can reproduce it on Windows SRCDS, otherwise this is gonna bog me down.

**Comment by danielga** [comment]
Reproduced this crash without the module. It's a Garry's Mod bug.
