### ISSUE TITLE
Crash just before a player loads in

### ISSUE THREAD

**Issue by Yogpod** [danielga/gm_sourcenet#47]
For once gmod actually gave something useful inside of /crashes
Running on Linux64, latest from update-lua-code
hook library is srlion's, if that might be important
Here's what it was doing before the crash
![image](https://user-images.githubusercontent.com/22012249/107077332-885b1c00-67a1-11eb-94e9-d59d0e15c848.png)
and the crash stacktrace

```
-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    0. WriteBits - [C]:-1
      1. WriteToBuffer - addons/administration/lua/sourcenet/netmessages.lua:728
        2. func - addons/administration/lua/sourcenet/incoming.lua:39
          3. (null) - addons/administration/lua/includes/modules/hook.lua:198

  MenuSystem
    Lua Interface = NULL

-Console Buffer-
================
```
![image](https://user-images.githubusercontent.com/22012249/107085455-5ea7f200-67ad-11eb-8b1e-b4f4eab14443.png)
image of said line inside of the WriteToBuffer function of clc_GMod_ClientToServer

& There's another crash where if i try to use voice chat, the server crashes, here's the same thing for above

![image](https://user-images.githubusercontent.com/22012249/107099902-c0755580-67c7-11eb-8570-cd137354d3c2.png)

```
-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    0. ReadBits - [C]:-1
      1. (null) - addons/administration/lua/sourcenet/netmessages.lua:1130
        2. xpcall - [C]:-1
          3. HandleStream - addons/administration/lua/sourcenet/outgoing.lua:42
            4. func - addons/administration/lua/sourcenet/outgoing.lua:80
              5. (null) - addons/administration/lua/includes/modules/hook.lua:198

  MenuSystem
    Lua Interface = NULL

-Console Buffer-
================
```

**Comment by danielga** [comment]
>Linux64

This module doesn't have builds for the `x86-64` Garry's Mod branch. Is that the branch you're using?

**Comment by Yogpod** [comment]
Yes i built them myself, are they unsupported right now?

**Comment by danielga** [comment]
`x86-64` is definitely unsupported, it keeps changing around and I don't have time to constantly keep on top of those changes. That said, I was able to reproduce the voicechat crash but not the first issue.

**Comment by Yogpod** [comment]
Ah gotcha, first issue i think i solved by adding a nil check to self.data, so not really a problem

**Comment by danielga** [comment]
That's weird, if `self.bits > 0` is true, so should `self.data ~= nil` be.

**Comment by danielga** [comment]
Ah, it actually isn't, nice catch.

**Comment by danielga** [comment]
Please try the [latest build](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.12).

**Comment by danielga** [comment]
Oh, and don't forget to update the Lua files, I force-pushed some changes.

**Comment by Yogpod** [comment]
Seems to be resolved now, thanks
