### ISSUE TITLE
Crash on mapchange

### ISSUE THREAD

**Issue by Yogpod** [danielga/gm_sourcenet#48]
server:
 linux64
 running TTT
 latest stuff from update-lua branch

steps to reproduce
1. join server
2. change to a different map
3.  it'll crash with nothing useful inside of crash dumps/debug.log, just that lua panicked/an empty crash report
here's the console before the segfault

![image](http://pls.propkill.me/2OkR.png)

this spawncount = -1 seems to be a consistent thing, might be it?
![imahe](http://pls.propkill.me/UXB9.png)

seems to be fine on win64

**Comment by danielga** [comment]
How are you testing this module with the `x86-64` branch of Garry's Mod? There's no builds for it.

**Comment by Yogpod** [comment]
Building myself

**Comment by danielga** [comment]
Using the `x86-64-support-sourcesdk` branch of `garrysmod_common` and project generator version 3?

**Comment by Yogpod** [comment]
```
git clone --recursive -b x86-64-support-sourcesdk https://github.com/danielga/garrysmod_common.git
git clone --recursive -b update-lua-code https://github.com/danielga/gm_sourcenet.git
cd gm_sourcenet
gm_sourcenet$ ./premake5 --gmcommon=/home/yogpod/garrysmod_common gmake
gm_sourcenet$ cd projects/linux/gmake
gm_sourcenet/projects/linux/gmake$ make config=release_x86_64
``` Yes

**Comment by danielga** [comment]
As a temporary workaround, `releasewithsymbols_x86_64` doesn't seem to crash. I'll need to spend some more time with the stripped symbols release build to understand what's going on.

**Comment by danielga** [comment]
Well, it was simpler than I thought and it makes no damn sense. `release_x86_64` enables link time optimization while `releasewithsymbols_x86_64`. As such, I disabled it on `release_x86_64` for testing and it won't crash anymore...

**Comment by Yogpod** [comment]
Ah, thank you i'll build latest and test

**Comment by Yogpod** [comment]
seems to have stopped the crashes

**Comment by danielga** [comment]
I've made some changes on `garrysmod_common` that should fix this crashing issue. Don't forget to pull the latest changes from this repo too.

**Comment by danielga** [comment]
Closing the issue as this should be fixed.
