### ISSUE TITLE
64 bit linux builds.

### ISSUE THREAD

**Issue by Synkstar** [danielga/gm_sourcenet#49]
I tried to compile it using the 64 bit version of garrysmod_common
I try to run premake it says this:
`Error: /usr/bin/bitmap:1: unexpected symbol near '<\127>'`
I can compile the 32 bit version fine using the regular garrysmod_common and if I force it to compile under 64 bit it spews out a bunch of compiler errors as expected.

**Comment by Synkstar** [comment]
Distro: Arch
Premake ver: 5.0.0-alpha15
I got it to try and compile by removing the bitmap include from sourcesdk-minimal. but its probably used in the project so it doesnt actually compile... The strange part is that it compiles the 32 bit version fine. I did make config=release_x86_64 because by removing the bitmap premake worked.

**Comment by Synkstar** [comment]
Wait nvm I got it to compile. Just cloned an updated version of the sourcesdk-minimal and removed the bitmap requirement from the premake.lua in it....

**Comment by Synkstar** [comment]
Ima reopen because yeah it does compile but it doesnt load on gmod and just says there is an error

**Comment by Synkstar** [comment]
Nvm im dumb I compiled it on a server running ubuntu and it compiled with no issues and loaded in gmod. Im guessing arch has some different things probably

**Comment by danielga** [comment]
Yeah, Arch is not really supported, I'm not even sure Garry's Mod runs on it.

**Comment by Synkstar** [comment]
Gmod runs on it good actually. I got it to load but it doesnt filter commands it just says like failed to filter for some reason. Probably because im using it wrong or something
