### ISSUE TITLE
linux release not working

### ISSUE THREAD

**Issue by timeVtr** [danielga/gm_sourcenet#50]
sourcenet release not working on linux: tried on ubuntu 18.04 and my host's Linux system. Used gmsv_sourcenet_linux.dll

I'm not really comfortable compiling it from scratch because I don't know much about bash scripting. :(

The module will load, but won't do anything when I try logging net messages by typing "sourcenet_netmessage_info 1" in console after loading outgoing.lua, which loads server.lua and netmessages.lua. No visible errors or concommand error either. 

Thanks

**Comment by timeVtr** [comment]
And if it helps, I'm getting the following error after a steamupdate on WINDOWS: 
![image](https://user-images.githubusercontent.com/73934027/118006232-b3a95600-b310-11eb-8bb7-3731b3395a4f.png)

This may or may not be related to the linux issue I'm having, but I'm not seeing any errors like this in linux. I'm mostly interested in getting linux to work because that's where I host my server on. I was just trying it out on Windows to compare.

**Comment by danielga** [comment]
The `CBaseServer::RecalculateTags` issue is fixed. Will be looking at why the module seems to be doing nothing.

**Comment by timeVtr** [comment]
> 
> 
> The `CBaseServer::RecalculateTags` issue is fixed. Will be looking at why the module seems to be doing nothing.

I think it has to do with having both client/server in premake5.lua. I removed the serverside=false section and figured out how to compile gmsv_sourcenet_linux.dll myself, and it works fine for me. 

Here is the premake5.lua I used to compile it, and it works. 

`

PROJECT_GENERATOR_VERSION = 2
      
      
        

      
      
        newoption({
      
      
        	trigger = "gmcommon",
      
      
        	description = "Sets the path to the garrysmod_common (https://github.com/danielga/garrysmod_common) directory",
      
      
        	value = "path to garrysmod_common directory"
      
      
        })
      
      
        

      
      
        local gmcommon = assert("/home/ubuntu/Documents/garrysmod_common",
      
      
        	"you didn't provide a path to your garrysmod_common (https://github.com/danielga/garrysmod_common) directory")
      
      
        include(gmcommon)
      
      
        

      
      
        CreateWorkspace({name = "sourcenet", abi_compatible = true})
      
      
        	CreateProject({serverside = true})
      
      
        		IncludeLuaShared()
      
      
        		IncludeHelpersExtended()
      
      
        		IncludeSDKCommon()
      
      
        		IncludeSDKTier0()
      
      
        		IncludeSDKTier1()
      
      
        		IncludeSDKLZMA()
      
      
        		IncludeScanning()
      
      
        		IncludeDetouring()
      
      
        		<span class="pl-c1">files</span>({<span class="pl-s"><span class="pl-pds">"</span>source/server/*.cpp<span class="pl-pds">"</span></span>, <span class="pl-s"><span class="pl-pds">"</span>source/server/*.hpp<span class="pl-pds">"</span></span>})

`

**Comment by danielga** [comment]
I've got a possible fix coming up on [this version](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.14-rc1).

**Comment by timeVtr** [comment]
> 
> 
> I've got a possible fix coming up on [this version](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.14-rc1).

release still not working on linux fyi

**Comment by danielga** [comment]
If you run this piece of Lua code, along with sourcenet's `incoming.lua` and `outgoing.lua` do you see anything being printed?
```lua
hook.Add("PreProcessMessages", "test", print)
hook.Add("PreSendDatagram", "test", print)
```

**Comment by Headshotz** [comment]
PreProcessMessages works fine for me. But PreSendDatagram is not working.
I already included outgoing and incoming in lua.

![image](https://user-images.githubusercontent.com/41658916/120116397-da281780-c17f-11eb-8085-1f612ad9c936.png)
![image](https://user-images.githubusercontent.com/41658916/120116400-de543500-c17f-11eb-99c8-ecd3d3aef2e8.png)

**Comment by timeVtr** [comment]
> 
> 
> PreProcessMessages works fine for me. But PreSendDatagram is not working.
> I already included outgoing and incoming in lua.
> 
> ![image](https://user-images.githubusercontent.com/41658916/120116397-da281780-c17f-11eb-8085-1f612ad9c936.png)
> ![image](https://user-images.githubusercontent.com/41658916/120116400-de543500-c17f-11eb-99c8-ecd3d3aef2e8.png)

Yep, I'm seeing the same results as this. I guess it's just Outgoing messages that are having issues.

**Comment by danielga** [comment]
Fixed something on garrysmod_common and [tagged a new release](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.14-rc2).
There's a caveat: to hook `PreSendDatagram`, you need a valid `CNetChan`, which requires players.

**Comment by timeVtr** [comment]
> 
> 
> Fixed something on garrysmod_common and [tagged a new release](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.14-rc2).
> There's a caveat: to hook `PreSendDatagram`, you need a valid `CNetChan`, which requires players.

Works now! Thanks for all your help!
