### ISSUE TITLE
GetSteamID returns STEAM_0:0:0 instead of the users steam id. 

### ISSUE THREAD

**Issue by Synkstar** [danielga/gm_sourcenet#51]
I was looking for a way to kick a player while they are still joining from the netchannel and this would be perfect. 
I was using it from GetAddress().

Thanks.

**Comment by danielga** [comment]
`GetAddress` returns the client's address from which they're connecting. This can be either an IP address or a SteamID (Steam peer-to-peer). In this case, it seems the client is not connecting through SteamP2P.
Doesn't seem like `CNetChan` provides SteamIDs.

**Comment by Synkstar** [comment]
In this file: https://github.com/danielga/gm_sourcenet/blob/master/source/netadr.cpp it adds a function that you can call from the GetAddress() along with get ip and get port so I just assumed that it would be a way to get someones steamid so you could kick them when they are still joining or if they are in a half connected state for example because they wouldn't be in player.GetAll() and in theory they could flood the server. Unless you know of another way to find their steamid from the netchannel while they are in a half connected state

**Comment by danielga** [comment]
The SteamID you get from that `netadr_t` is the SteamP2P "address" that identifies them. AFAIK there's no way to get a validated SteamID before these Lua hooks happen https://wiki.facepunch.com/gmod/GM:NetworkIDValidated https://wiki.facepunch.com/gmod/GM:PlayerAuthed
