### ISSUE TITLE
Compile for GLIBC_2.17 pls

### ISSUE THREAD

**Issue by DmitriyH-prog** [danielga/gm_sourcenet#52]
(temporary) /lib/libm.so.6: version `GLIBC_2.29' not found (required by /home/server3165/game/garrysmod/lua/bin/gmsv_sourcenet_linux.dll)
(temporary) Couldn't load module library!

**Comment by danielga** [comment]
What OS are you running the module on? It's currently being compiled on Azure Pipelines Ubuntu 16.04 (Xenial), which should be using glibc 2.23. That release is already over 5 years old.

**Comment by danielga** [comment]
Also, the error is coming from your `/lib/libm.so.6`, which is requiring GLIBC 2.29. My module links with libm.

**Comment by DmitriyH-prog** [comment]
Can you compile for GLIBC 2.17?

**Comment by willox** [comment]
compile it yourself

**Comment by danielga** [comment]
> Can you compile for GLIBC 2.17?

I already do GLIBC 2.23 and that's already too old. Besides that, the problem is coming from your configuration. One of your system binaries (libm) requires GLIBC 2.29, which it can't find for some reason.

**Comment by danielga** [comment]
The [latest build](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.15-rc1) should work with glibc 2.15.
