### ISSUE TITLE
Sourcenet Client crashes

### ISSUE THREAD

**Issue by LastPlayerTR** [danielga/gm_sourcenet#58]
It crashes when require module.

Dump : 
[692e1f0d-398a-408e-8f94-be95b2f5c364.zip](https://github.com/danielga/gm_sourcenet/files/8564505/692e1f0d-398a-408e-8f94-be95b2f5c364.zip)

**Comment by LastPlayerTR** [comment]
Version :  1.1.15-rc1
 Latest

OS : Windows 10 Home X64
Branch : 86-64x Garry's Mod 32 bit launch

**Comment by danielga** [comment]
The `x86-64` is not officially supported. The builds provided here are only for the main branch of Garry's Mod.
