### ISSUE TITLE
SendLuaFile crash

### ISSUE THREAD

**Issue by klen-list** [danielga/gm_sourcenet#59]
Seems `SendLuaFile` is crashing because doesn't have builded crc table when calcing crc for string
![изображение](https://user-images.githubusercontent.com/49125075/179181139-e018351f-7424-4775-ada3-f7d4851b3487.png)

**Comment by danielga** [comment]
Should be fixed with [this release candidate](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.15-rc2) (currently building).

**Comment by klen-list** [comment]
Yea, thanks, it works, but now I have this warning on the client when sending lua
```
Couldn't extract from datatable (lua/includes/util.lua) (36)
```

**Comment by klen-list** [comment]
it 2 fileid in example, for other files this produce warning too `Couldn't extract from datatable (lua/file/path) (36)`
maybe compressing or crc have invalid setup?

**Comment by danielga** [comment]
I believe I fixed it [in this version](https://github.com/danielga/gm_sourcenet/releases/tag/1.1.15-rc3). The hashing algorithm of the files changed from CRC32 (😂) to SHA256.

**Comment by klen-list** [comment]
Now fully works, thanks!
