### ISSUE TITLE
[ERROR] failed to locate CBaseClient::ConnectionStart

### ISSUE THREAD

**Issue by FarikLoL** [danielga/gm_sourcenet#61]
[ERROR] failed to locate CBaseClient::ConnectionStart
  1. unknown - [C]:-1
   2. require - [C]:-1
    3. unknown - lua/1.lua:2

require("sourcenet")

Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 18:26:23 Jan  9 2023 (8829) (4000)
GMod version 2023.02.10, branch: unknown, multicore: 0
Windows 32bit

**Comment by danielga** [comment]
Can you try [the latest release](https://github.com/danielga/gm_sourcenet/releases/tag/1.5.17-rc1) please?
