### ISSUE TITLE
Incorrect clc_GMod_ClientToServer Behaviour

### ISSUE THREAD

**Issue by Meachamp** [danielga/gm_sourcenet#7]
The issue stems from commit 511f59216da360c75552f656645eaf5579308f73, here: https://github.com/danielga/gm_sourcenet/commit/511f59216da360c75552f656645eaf5579308f73#diff-f90e1aa148414a0e45fa662cd4387f89R337

You perform the bit calculation twice, resulting in a negative bit value. The ReadBits() call errors, doesn't reflect the data to the net channel, and results in a player not being able to join. 

Thank you, by the way, for putting the effort in to reverse engineer all this. It was made debugging net messages a breeze.

**Comment by danielga** [comment]
Thanks for the report. This issue was fixed on the `x64-branch` and is awaiting further changes on other repositories it depends on. You can, however, get the fixed file now.
